---
# Train Controller Deployment
- name: deploy the latest tain controller code.
  hosts: all
  user: portaj
  sudo: yes

  vars:
    node_tarball: "node-v{{ node_version }}-{{ node_arch }}.tar.gz"
    node_tempdir: "node-v{{ node_version }}-{{ node_arch }}"

  roles:
  - common
  - nodejs
  - train
  - headless
